# Generated by Django 3.1.5 on 2021-02-02 14:34

import django.contrib.auth.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('reg_confirmed_date', models.DateTimeField()),
                ('about_yourself', models.TextField()),
                ('avatar', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos/'), upload_to='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posted_time', models.DateTimeField()),
                ('edited_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangogramm.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posted_time', models.DateTimeField()),
                ('edited_time', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangogramm.account')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_itself', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos/'), upload_to='')),
                ('description', models.TextField()),
                ('picture_preview', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos/'), upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangogramm.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangogramm.account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.comment')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.picture')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.post'),
        ),
    ]
