# Generated by Django 3.1.5 on 2021-04-14 12:52

from django.db import migrations
import djangogramm.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0002_auto_20210321_1351'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', djangogramm.models.AccountManager()),
            ],
        ),
    ]
