# Generated by Django 3.1.5 on 2021-03-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0002_auto_20210311_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirmation_token',
        ),
    ]
