# Generated by Django 3.1.5 on 2021-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0003_auto_20210215_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture_preview',
        ),
        migrations.AlterField(
            model_name='account',
            name='reg_confirmed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
