# Generated by Django 3.1.5 on 2021-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0004_auto_20210215_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_confirmed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
