# Generated by Django 3.1.5 on 2021-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0007_auto_20210216_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
