# Generated by Django 3.1.5 on 2021-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0009_auto_20210217_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_itself',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
