# Generated by Django 3.1.5 on 2021-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0010_auto_20210217_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_itself',
            field=models.ImageField(upload_to='media/photos/%Y/%m/%d/'),
        ),
    ]
