# Generated by Django 3.1.5 on 2021-02-17 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0011_auto_20210217_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
