# Generated by Django 3.1.5 on 2021-02-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0016_auto_20210217_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['posted_time']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-loading_time']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_time']},
        ),
        migrations.AddField(
            model_name='account',
            name='confirmation_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
