# Generated by Django 3.1.5 on 2021-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0017_auto_20210218_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_confirmed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
