# Generated by Django 3.1.5 on 2021-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0018_auto_20210226_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about_yourself',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=2200),
        ),
    ]
